### PR TITLE
Adding mercury and onahau colours

### PR DESCRIPTION
**Pull request by rogerfranklin2**
Starting of moving out colours to toolkit

### CODE REVIEW

**Comment by peter-mouland** [comment]
oh wow - mercury and  onahau.

I see these is following the existing method so this PR gets a thumbs up from me  👍


...but, i guess we should have a time out and decide if this is easy-to-use going forward i.e. what colour is `onahau`? or, indeed, does it actually matter?

**Comment by rogerfranklin2** [comment]
I had the same problem at nowtv when it came to naming colours. I use an osx app called sip and that gives you a name when you give it a colour.

screen shot 2016-10-17 at 14 51 04

**Comment by rogerfranklin2** [comment]
I think this is another thing that can be added to the documentation list as it would be good to maintain a list of colours which are used

**Comment by rogerfranklin2** [comment]
Looking at other projects. https://github.com/notonthehighstreet/checkout-frontend/blob/e011a24cc2f81945332789605ddbf4f7aa2335e7/app/styles/common/_variables.scss

```
$GRAY_COLOR: #eae8e6;
$GRAY_MID_COLOR: #888;
$GRAY_MID_COLOR_2: #949494;
$GRAY_MID_LIGHT_COLOR: #ccc;
$GRAY_LIGHT_COLOR: #bab4ad;
$GRAY_LIGHT_2: #cac5bf;
$GRAY_LIGHTER_COLOR: #e4e1dc;
$GRAY_LIGHTEST_COLOR: #f6f5f3;
```

to me that is just as cryptic as using random colour names.

**Comment by peter-mouland** [comment]
yeah, true - just a case of getting use to it i guess

**Pull request merged**
